# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
# Mod Properties
mod_version=1.1.0
maven_group=com.pixelz
# Loom 1.14 is recommended for 1.21.11 (https://fabricmc.net/2025/12/05/12111.html)
# Use 1.14.x - latest patch for 1.14 series
loom_version=1.14.10
fabric_version=0.141.6+1.21.11
